spring:
  application:
    name: hazard
  jackson:
    serialization:
      indent-output: true
  sql:
    init:
      mode: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;NON_KEYWORDS=YEAR,REFERENCE,COMMENT,INDEX
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: toxval
    defer-datasource-initialization: false
    hibernate.ddl-auto: none

# logging
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    gov.epa.ccte.api.*: debug
    org.springframework: warn