name: Application-security-scan

on:
  push:
   branches: [ dev, staging, dev-756 ]
    
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Permissions
      run: chmod -R 777 /zap/wrk  
      
    - name: perform passive scan
      uses: zaproxy/action-api-scan@v0.6.0
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         format: openapi
         target: 'https://api-ccte-stg.epa.gov/docs/hazard.json'
         cmd_options: '-r passive'
