name: Application-security-scan

on:
  push:
   branches: [ "dev", "staging", zap-scan-modification ]
    
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
     - name: perform passive scan
       uses: zaproxy/action-api-scan@v0.6.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         format: openapi
         target: 'https://api-ccte-stg.epa.gov/docs/hazard.json'
         api-key: ${{ secrets.X_API_KEY }}
        #include the alpha passive scan rules as well
         cmd_options: '-a'
         
